# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2d62e5aa339a3299283948bd16b87be16c4412a102520ae4af86c2acbb828318e465b68774c40ffbe5394c6c635266af8e5889d44b7c4b14cd1088a0f33af8c

test:
  secret_key_base: 16cc0c76a82c66a0784a692442bca67b14d8019f34ccb55cbc4dbfc4269a82c9ce8ccf093660f8037119cf14213e9d922018ec49220c7484fc14dd3c583fb91a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
